input {
  tcp {
    port => 5000
    codec => json
    type => "json_event"
  }
}

filter {
  # Extraire le nom d'index depuis _index_hint si présent
  if [_index_hint] {
    mutate {
      add_field => { "[@metadata][target_index]" => "%{_index_hint}" }
      remove_field => [ "_index_hint" ]
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "logs-forensic-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout { codec => rubydebug }
}

